# Empty and omitted keys will use default values
InstallDir:
WriteDirectory:
Verbose:
AllPacks:
LogLevel: info
Run: # must be all-lowercase
  - kubernetes
  # - "kubernetes"
  # - "storage"
ServicePacks:
  Kubernetes:
    TagInclusions:
      #- k-pod
    TagExclusions:
    KubeConfig: poop
    KubeContext:
    AuthorisedContainerImage: citihubprod.azurecr.io/citihub/probr-probe # required
    UnauthorisedContainerImage: docker.io/citihub/probr-probe # required
    SystemNamespace: kube-system
    DashboardPodNamePrefix: kubernetes-dashboard
  Storage:
    Provider: Azure # if object OR required vars within it are omitted, pack will not be included
CloudProviders:
  Azure:
    TenantID: ""
    SubscriptionID: ""
    ClientID: ""
    ClientSecret: ""
    ManagementGroup:
    ResourceGroup: ProbrRG
    ResourceLocation: "westeurope"
    Identity:
      DefaultNamespaceAI:
      DefaultNamespaceAIB:
